hdfc_policy = [
    "ABCD Chronic Care Policy Policy",
    "Arogya Sanjeevani Policy Group Policy",
    "Arogya Sanjeevani Policy Retail Policy",
    "Card Sure Package Insurance Policy",
    "Critical Advantage Rider Policy",
    "Critical Illness Policy Policy",
    "Dengue CIS Policy",
    "Group Health Insurance Policy",
    "Group Mediclaim Insurance Policy",
    "HDFC Ergo Secure 4-in-1 Policy",
    "HDFC Group Health Insurance Policy",
    "Home Credit Assure Policy",
    "Hospital Cash (Sep 2021) Policy",
    "Hospital Daily Cash Policy",
    "IPA Rider Policy",
    "Janata Personal Accident CIS Policy",
    "Limitless Policy",
    "Mosquito Disease Protection Policy Group Policy",
    "MyHealth Critical Illness Policy",
    "MyHealth Suraksha Hospital Cash Add-on Policy",
    "Optima Restore (Revision) Policy",
    "Optima Secure (Revision) Policy",
    "Optima Wellbeing (Add-on) Policy",
    "Parenthood Policy",
    "Pradhan Mantri Suraksha Bima Yojana (PMSBY) Policy",
    "Protector Rider (Sep 2021) Policy",
    "Saral Bima Suraksha Policy",
    "Sarv Suraksha Plus Group Policy",
    "Surrogacy and Oocyte Protect Policy",
    "Unlimited Restore (Add-on) Policy",
    "HDFC Home Insurance Policy",
    "Home Credit Assure (Brochure) Policy",
    "Home Shield (Brochure CTC) Policy",
    "EMI Protector Plus PCV Annual Policy",
    "EMI Protector Plus PC Annual Policy",
    "EMI Protector Plus PC Bundled Policy",
    "EMI Protector Plus PC SAOD Policy",
    "EV Motor Add-ons Private Car Annual Policy",
    "EV Motor Add-ons Private Car Bundled Policy",
    "EV Motor Add-ons Private Car SAOD Policy",
    "EV Motor Add-ons Two Wheeler Annual Policy",
    "EV Motor Add-ons Two Wheeler Bundled Policy",
    "EV Motor Add-ons Two Wheeler SAOD Policy",
    "Motor Insurance Pricing Revision (Private Cars) Policy",
    "Return to Invoice PC Annual Policy",
    "Return to Invoice PC Bundled Policy",
    "Return to Invoice PC SAOD Policy",
    "Return to Invoice PCV Annual Policy",
    "Standalone Third Party Long Term Two Wheeler Insurance Policy Policy",
    "Toyota Add-on Covers PCV Policy",
    "Toyota Add-on Covers Private Car Policy",
    "Beyond Borders Policy",
    "Griha Brochure (UID 7869) Policy",
    "Group Travel Insurance Policy",
    "HDFC Ergo Explorer Policy",
    "Student Suraksha Overseas Travel FAQ Policy",
    "Student Travel HDFC Policy",
    "Travel Insurance Policy",
    "Travelsure (Group) Policy",
    "TravelX Policy"
]
