bajaj_policy = [
    "Arogya Sanjeevani Policy Bajaj",
    "Bajaj Allianz Policy",
    "Bajaj Waiver Policy",
    "Corona Kavach Policy Wordings Bajaj Policy",
    "Critical Illness Bajaj Policy",
    "Criti Care Bajaj Policy",
    "Extra Care Plus Bajaj Policy",
    "Global Personal Guard Policy (Individual) Bajaj Policy",
    "Global Health Care Bajaj Policy",
    "HDFC Home Insurance Policy",
    "Health Care Supreme Bajaj Policy",
    "Health Guard CIS Print Bajaj Policy",
    "Health Infinity Bajaj Policy",
    "Health Ensure Bajaj Policy",
    "Loan Care Bajaj Policy",
    "My Health Care Plan 1 Bajaj Policy",
    "M Care Bajaj Policy",
    "Nidaan Swasthya Bima Bajaj Policy",
    "Personal Accident Bajaj Policy",
    "Premium Personal Guard Bajaj Policy",
    "Sankat Mochan Bajaj Policy",
    "Saral Suraksha Bima Bajaj Policy",
    "Silver Health Bajaj Policy",
    "Star Package Bajaj Policy",
    "Tax Gain Bajaj Policy"
]
